require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CreateRequestSkillsController do

  # This should return the minimal set of attributes required to create a valid
  # CreateRequestSkill. As you add validations to CreateRequestSkill, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CreateRequestSkillsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all create_request_skills as @create_request_skills" do
      create_request_skill = CreateRequestSkill.create! valid_attributes
      get :index, {}, valid_session
      assigns(:create_request_skills).should eq([create_request_skill])
    end
  end

  describe "GET show" do
    it "assigns the requested create_request_skill as @create_request_skill" do
      create_request_skill = CreateRequestSkill.create! valid_attributes
      get :show, {:id => create_request_skill.to_param}, valid_session
      assigns(:create_request_skill).should eq(create_request_skill)
    end
  end

  describe "GET new" do
    it "assigns a new create_request_skill as @create_request_skill" do
      get :new, {}, valid_session
      assigns(:create_request_skill).should be_a_new(CreateRequestSkill)
    end
  end

  describe "GET edit" do
    it "assigns the requested create_request_skill as @create_request_skill" do
      create_request_skill = CreateRequestSkill.create! valid_attributes
      get :edit, {:id => create_request_skill.to_param}, valid_session
      assigns(:create_request_skill).should eq(create_request_skill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CreateRequestSkill" do
        expect {
          post :create, {:create_request_skill => valid_attributes}, valid_session
        }.to change(CreateRequestSkill, :count).by(1)
      end

      it "assigns a newly created create_request_skill as @create_request_skill" do
        post :create, {:create_request_skill => valid_attributes}, valid_session
        assigns(:create_request_skill).should be_a(CreateRequestSkill)
        assigns(:create_request_skill).should be_persisted
      end

      it "redirects to the created create_request_skill" do
        post :create, {:create_request_skill => valid_attributes}, valid_session
        response.should redirect_to(CreateRequestSkill.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved create_request_skill as @create_request_skill" do
        # Trigger the behavior that occurs when invalid params are submitted
        CreateRequestSkill.any_instance.stub(:save).and_return(false)
        post :create, {:create_request_skill => {}}, valid_session
        assigns(:create_request_skill).should be_a_new(CreateRequestSkill)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CreateRequestSkill.any_instance.stub(:save).and_return(false)
        post :create, {:create_request_skill => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested create_request_skill" do
        create_request_skill = CreateRequestSkill.create! valid_attributes
        # Assuming there are no other create_request_skills in the database, this
        # specifies that the CreateRequestSkill created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CreateRequestSkill.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => create_request_skill.to_param, :create_request_skill => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested create_request_skill as @create_request_skill" do
        create_request_skill = CreateRequestSkill.create! valid_attributes
        put :update, {:id => create_request_skill.to_param, :create_request_skill => valid_attributes}, valid_session
        assigns(:create_request_skill).should eq(create_request_skill)
      end

      it "redirects to the create_request_skill" do
        create_request_skill = CreateRequestSkill.create! valid_attributes
        put :update, {:id => create_request_skill.to_param, :create_request_skill => valid_attributes}, valid_session
        response.should redirect_to(create_request_skill)
      end
    end

    describe "with invalid params" do
      it "assigns the create_request_skill as @create_request_skill" do
        create_request_skill = CreateRequestSkill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CreateRequestSkill.any_instance.stub(:save).and_return(false)
        put :update, {:id => create_request_skill.to_param, :create_request_skill => {}}, valid_session
        assigns(:create_request_skill).should eq(create_request_skill)
      end

      it "re-renders the 'edit' template" do
        create_request_skill = CreateRequestSkill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CreateRequestSkill.any_instance.stub(:save).and_return(false)
        put :update, {:id => create_request_skill.to_param, :create_request_skill => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested create_request_skill" do
      create_request_skill = CreateRequestSkill.create! valid_attributes
      expect {
        delete :destroy, {:id => create_request_skill.to_param}, valid_session
      }.to change(CreateRequestSkill, :count).by(-1)
    end

    it "redirects to the create_request_skills list" do
      create_request_skill = CreateRequestSkill.create! valid_attributes
      delete :destroy, {:id => create_request_skill.to_param}, valid_session
      response.should redirect_to(create_request_skills_url)
    end
  end

end
